from enum import StrEnum


class Permission(StrEnum):
    MANAGE_USERS = "MANAGE_USERS"

    CREATE_REQUEST = "CREATE_REQUEST"
    EDIT_OWN_REQUEST = "EDIT_OWN_REQUEST"
    SUBMIT_OWN_REQUEST = "SUBMIT_OWN_REQUEST"
    VIEW_OWN_REQUESTS = "VIEW_OWN_REQUESTS"
    MANAGE_OWN_ATTACHMENTS = "MANAGE_OWN_ATTACHMENTS"

    VIEW_REQUESTS = "VIEW_REQUESTS"
    VIEW_REQUEST_HISTORY = "VIEW_REQUEST_HISTORY"
    DOWNLOAD_ATTACHMENTS = "DOWNLOAD_ATTACHMENTS"
    REVIEW_REQUEST = "REVIEW_REQUEST"
    REQUEST_CORRECTION = "REQUEST_CORRECTION"
    APPROVE_REQUEST = "APPROVE_REQUEST"
    REJECT_REQUEST = "REJECT_REQUEST"
    CHANGE_REQUEST_STATUS = "CHANGE_REQUEST_STATUS"

    MANAGE_FORMS = "MANAGE_FORMS"
    VIEW_FORMS = "VIEW_FORMS"

    VIEW_AUDIT = "VIEW_AUDIT"
    VIEW_SECURITY_AUDIT = "VIEW_SECURITY_AUDIT"
